let errors = {}
errors.missingPassword = 'No password was given.';
errors.incorrectPassword = 'Password or username is incorrect.';
errors.incorrectUsername = 'Password or username is incorrect.';
errors.missingUsername = 'No username was given.';
errors.userExists = 'A user exists with that name.';
errors.createPassword = 'An error occured while securing your password.'
errors.unknown = 'An unknown error occured while processing the request. If this persists, please contact support';
module.exports = errors;
